### ISSUE TITLE
Add elexon forecast to graph

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/analysis-dashboard#172]
## Detailed Description
Add elexon forecast to forecast graph

## Context
- forecast code is in here - https://github.com/openclimatefix/analysis-dashboard/blob/main/src/forecast.py
- need to set DB_URL inorder to run this locally and connect using ssh_tunnel

## Possible Implementation
- Add elexonpy to requirements 
- show 3 different forecast - process type = "Day Ahead", "Intraday Process", "Intraday Total"
- Go to "Forecast page"

**Comment by 14Richa** [comment]
Hey  @peterdudfield , i can work on this.
