### ISSUE TITLE
Change Forecast initial estimate to be dashed line and updated to be solid

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/analysis-dashboard#173]
Currently the lines in the "forecast" page of analysis dashboard look like this: 
![image](https://github.com/user-attachments/assets/cb9dd709-b996-451b-abf8-3054da412060)

It would make sense to make them consistent with the UI, where they are dashed for initial estimate. 

We could swap the lines in the quartz UI, but the dashed line is harder to read the details of the line with the pieces missing in the dashes, so I'd propose to change to match quartz UI.

**Comment by peterdudfield** [comment]
This is fixed in the latest version, just need to deploy it. version - [939b030](https://github.com/openclimatefix/analysis-dashboard/commit/939b030ab8ad322282f7cbb6d2e6a28ef597aa77)
