### ISSUE TITLE
add site name to site forecast

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/analysis-dashboard#217]
add site name to site forecast page, we currently on see uuid

![Screenshot 2024-11-14 at 09 22 39](https://github.com/user-attachments/assets/656e2400-2802-495d-8259-46ed5bc8e174)

**Comment by zealous-ideal-monk** [comment]
in which file can i find these codes

**Comment by peterdudfield** [comment]
hi @zealous-ideal-monk, sorry ive done this already. Ill close this
